name: ekman
description: Face recognition application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.5
  camera: ^0.5.8+2
  path_provider: ^1.6.9
  path: ^1.7.0
  firebase_ml_vision: ^0.9.4
  flutter_emoji: ^2.2.1+1
  native_device_orientation: ^0.3.0


dev_dependencies:

flutter:
  uses-material-design: true

  assets:
  - images/
